### ISSUE TITLE
Problems in Ninjia build

### ISSUE THREAD

**Issue by tangyuelm** [Tiiiger/QPyTorch#45]
Dear Sir/Madam,

Thanks for your open source codes. I want to use it to do some experiments on fixed-16 points but got such errors:**
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1673, in _run_ninja_build
    env=env)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "alexnet16fix14.py", line 15, in <module>
    from qtorch.quant import fixed_point_quantize, block_quantize, float_quantize
  File "/home/ubuntu/.local/lib/python3.6/site-packages/qtorch/quant/__init__.py", line 1, in <module>
    from .quant_function import *
  File "/home/ubuntu/.local/lib/python3.6/site-packages/qtorch/quant/quant_function.py", line 29, in <module>
    os.path.join(current_path, "quant_cuda/quant.cu"),
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1091, in load
    keep_intermediates=keep_intermediates)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1302, in _jit_compile
    is_standalone=is_standalone)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1407, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'quant_cuda': [1/7] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output bit_helper.cuda.o.d -DTORCH_EXTENSION_NAME=quant_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/.local/lib/python3.6/site-packages/qtorch/quant/quant_cuda/bit_helper.cu -o bit_helper.cuda.o 
FAILED: bit_helper.cuda.o 
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output bit_helper.cuda.o.d -DTORCH_EXTENSION_NAME=quant_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/.local/lib/python3.6/site-packages/qtorch/quant/quant_cuda/bit_helper.cu -o bit_helper.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
[2/7] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output sim_helper.cuda.o.d -DTORCH_EXTENSION_NAME=quant_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/.local/lib/python3.6/site-packages/qtorch/quant/quant_cuda/sim_helper.cu -o sim_helper.cuda.o 
FAILED: sim_helper.cuda.o 
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output sim_helper.cuda.o.d -DTORCH_EXTENSION_NAME=quant_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/.local/lib/python3.6/site-packages/qtorch/quant/quant_cuda/sim_helper.cu -o sim_helper.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
[3/7] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output block_kernel.cuda.o.d -DTORCH_EXTENSION_NAME=quant_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/.local/lib/python3.6/site-packages/qtorch/quant/quant_cuda/block_kernel.cu -o block_kernel.cuda.o 
FAILED: block_kernel.cuda.o 
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output block_kernel.cuda.o.d -DTORCH_EXTENSION_NAME=quant_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/.local/lib/python3.6/site-packages/qtorch/quant/quant_cuda/block_kernel.cu -o block_kernel.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
[4/7] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output float_kernel.cuda.o.d -DTORCH_EXTENSION_NAME=quant_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/.local/lib/python3.6/site-packages/qtorch/quant/quant_cuda/float_kernel.cu -o float_kernel.cuda.o 
FAILED: float_kernel.cuda.o 
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output float_kernel.cuda.o.d -DTORCH_EXTENSION_NAME=quant_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/.local/lib/python3.6/site-packages/qtorch/quant/quant_cuda/float_kernel.cu -o float_kernel.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
[5/7] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output fixed_point_kernel.cuda.o.d -DTORCH_EXTENSION_NAME=quant_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/.local/lib/python3.6/site-packages/qtorch/quant/quant_cuda/fixed_point_kernel.cu -o fixed_point_kernel.cuda.o 
FAILED: fixed_point_kernel.cuda.o 
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output fixed_point_kernel.cuda.o.d -DTORCH_EXTENSION_NAME=quant_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/.local/lib/python3.6/site-packages/qtorch/quant/quant_cuda/fixed_point_kernel.cu -o fixed_point_kernel.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
[6/7] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output quant.cuda.o.d -DTORCH_EXTENSION_NAME=quant_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/.local/lib/python3.6/site-packages/qtorch/quant/quant_cuda/quant.cu -o quant.cuda.o 
FAILED: quant.cuda.o 
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output quant.cuda.o.d -DTORCH_EXTENSION_NAME=quant_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/.local/lib/python3.6/site-packages/qtorch/quant/quant_cuda/quant.cu -o quant.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
ninja: build stopped: subcommand failed.

**I used the the GPU from AWS server with ubuntu 18.04. Here is the detailed information****

ubuntu@ip-172-31-47-61:~/src/train$ python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 450.119.03
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] qtorch==0.3.0
[pip3] torch==1.8.0
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py37he8ac12f_0
[conda] mkl_fft                   1.2.1            py37h54f3939_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.19.2           py37h54aff64_0
[conda] numpy-base                1.19.2           py37hfa32c7d_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1

Could you provide me any suggestions? Thank you very much.

**Comment by Tiiiger** [comment]
hi @tangyuelm 

this looks like a cuda version error to me .... not sure why CUDA 10.2 is doing this though ...  perhaps you are loading the wrong CUDA? I see that you have multiple versions of cuda installed.

**Comment by tangyuelm** [comment]
Thanks for your attention. My original version was CUDA 10.0 which could not work. I tried to update it to CUDA 10.2 and it seems that I failed. I have re-updated it to CUDA 10.2 and not it seems to work. However, the accuracy is pretty low (less than 1%) when I try to test the fixed 16 bits on Imagenet (the original class num is 1000). I noticed that the example in your code uses the class num as 10. I am wondering if it can be extended to 1000 classes with an appropriate selection of FL.

**Comment by Tiiiger** [comment]
@tangyuelm 

sorry for a late reply, I was on vacation. I believe you might need to do a more involved change to get the example to work on imagenet. You need to change the network architecture to handle the correct resolution size, and might need to change the learning rate (and schedule). I have also not tested the precision setting for imagenet so it might not work. 

Please keep in mind that the example is more about demonstrating the usage of qpytorch instead of achieving the best accuracy. 

If you can build correctly, I believe things should work fine. so closing this for now.
